name: kuhaejwo_app
description: 건국대학교 쿨하우스 룸매 매칭 서비스
publish_to: "none" # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.18.4 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  flutter_svg: ^1.1.6
  get: ^4.6.1
  flutter_screenutil: ^5.3.1
  path_provider: ^2.0.9
  url_launcher: ^6.0.20
  dio: ^4.0.4
  shimmer: ^2.0.0
  cached_network_image: ^3.2.0
  logger: ^1.1.0
  flutter_inappwebview: ^5.4.4+3
  get_storage: ^2.0.3
  flutter_lints: ^2.0.0
  intl: ^0.17.0
  flutter_secure_storage: ^6.1.0
  dropdown_button2: ^1.9.1
  firebase_core: ^2.4.0
  firebase_auth: ^4.2.3
  flutter_chat_types: ^3.6.0
  flutter_firebase_chat_core: ^1.6.4
  mime: ^1.0.3
  open_filex: ^4.3.2
  flutter_chat_ui: ^1.6.6
  flutter_layout_grid: ^2.0.1
  linear_progress_bar: ^1.1.0
  cross_file: ^0.3.3+2
  http_parser: ^4.0.2
  image_picker: ^0.8.6
  firebase_messaging: ^14.2.1
  flutter_local_notifications: ^13.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/icons/
    - assets/images/
  fonts:
    - family: NotoSansKR
      fonts:
        - asset: assets/fonts/NotoSansKR-Black.otf
          weight: 900
        - asset: assets/fonts/NotoSansKR-Bold.otf
          weight: 700
        - asset: assets/fonts/NotoSansKR-Medium.otf
          weight: 500
        - asset: assets/fonts/NotoSansKR-Regular.otf
          weight: 400
        - asset: assets/fonts/NotoSansKR-Light.otf
          weight: 300
        - asset: assets/fonts/NotoSansKR-Thin.otf
          weight: 100
